spring.application.name=tp-complet
spring.main.lazy-initialization=true

library.database.url=jdbc:h2:mem:librarydb
library.database.username=sa
library.database.password=
library.database.driver-class-name=org.h2.Driver